// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFMDGVstKIIUj6Idl2ZOfVETYCXeySsQU',
    appId: '1:145028058708:web:c347c2241b4d0ba20327c1',
    messagingSenderId: '145028058708',
    projectId: 'e-commerce-app-40b91',
    authDomain: 'e-commerce-app-40b91.firebaseapp.com',
    storageBucket: 'e-commerce-app-40b91.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAszUKvsCv5cfxcdtdPUjUF8sKeNaM3WJY',
    appId: '1:145028058708:android:2acda5a973c5e7920327c1',
    messagingSenderId: '145028058708',
    projectId: 'e-commerce-app-40b91',
    storageBucket: 'e-commerce-app-40b91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF3IB2T_QVAkQlphCqhBY_62SakUamAzs',
    appId: '1:145028058708:ios:44bf50a11b79773f0327c1',
    messagingSenderId: '145028058708',
    projectId: 'e-commerce-app-40b91',
    storageBucket: 'e-commerce-app-40b91.firebasestorage.app',
    iosBundleId: 'com.example.blocApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF3IB2T_QVAkQlphCqhBY_62SakUamAzs',
    appId: '1:145028058708:ios:44bf50a11b79773f0327c1',
    messagingSenderId: '145028058708',
    projectId: 'e-commerce-app-40b91',
    storageBucket: 'e-commerce-app-40b91.firebasestorage.app',
    iosBundleId: 'com.example.blocApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFMDGVstKIIUj6Idl2ZOfVETYCXeySsQU',
    appId: '1:145028058708:web:97cc4fef17fbdcd20327c1',
    messagingSenderId: '145028058708',
    projectId: 'e-commerce-app-40b91',
    authDomain: 'e-commerce-app-40b91.firebaseapp.com',
    storageBucket: 'e-commerce-app-40b91.firebasestorage.app',
  );

}